site_url: 'https://icos-carbon-portal.github.io/pylib/'

site_name: ICOS Carbon Portal Python Libraries
nav:
    - About: index.md
    - icoscp:
        - About: icoscp/index.md
        - Installation: icoscp/install.md
        - Authentication: icoscp/authentication.md
        - Getting started with icoscp_core: icoscp/getting_started.md
        - Examples: icoscp/examples.md
        - Legacy icoscp modules: icoscp/modules.md
        - Legacy icoscp examples: icoscp/legacy_examples.md
        - FAQ: icoscp/faq.md
        - Changelogs:
            - icoscp: icoscp/changelog.md
            - icoscp_core: icoscp/changelogs/icoscp_core.md
    - icoscp_stilt:
        - About: icoscp_stilt/index.md
        - Getting started with the new icoscp_stilt: icoscp_stilt/getting_started.md
        - Legacy modules: icoscp_stilt/modules.md
        - Changelog: icoscp_stilt/changelog.md

markdown_extensions:
  - admonition

validation:
    links:
        anchors: warn

theme:
    name: readthedocs
    custom_dir: overrides
