site_url: 'https://icos-carbon-portal.github.io/pylib/icoscp_stilt/'

site_name: ICOS Carbon Portal icoscp_stilt Library
nav:
    - About: index.md
    - Getting started with the new icoscp_stilt: getting_started.md
    - Legacy modules: modules.md
    - Changelog: changelog.md

theme:
    name: readthedocs
