site_url: 'https://icos-carbon-portal.github.io/pylib/icoscp_stilt/'

site_name: ICOS Carbon Portal icoscp_stilt Library
nav:
    - About: index.md
    - Legacy modules: modules.md

theme:
    name: readthedocs
