site_url: 'https://icos-carbon-portal.github.io/pylib/icoscp/'

site_name: ICOS Carbon Portal icoscp Library
nav:
    - About: index.md
    - Installation: install.md
    - Getting started: getting_started.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Legacy modules: modules.md
    - Legacy examples: legacy_examples.md
   
#markdown_extensions:
#    - attr_list
  
theme:
    name: readthedocs
#    collapse_navigation: False
