site_url: 'https://icos-carbon-portal.github.io/pylib/icoscp/'

site_name: ICOS Carbon Portal icoscp Library
nav:
    - About: index.md
    - Installation: install.md
    - Authentication: authentication.md
    - Getting started with icoscp_core: getting_started.md
    - Examples: examples.md
    - Legacy icoscp modules: modules.md
    - Legacy icoscp examples: legacy_examples.md
    - FAQ: faq.md
    - Changelog: changelog.md

theme:
    name: readthedocs
